var OZON_FREE_POS={VERSION:'1.0.0',SHEET_ID:'1SHY1rz7XZeqOGkJSkitfSPlKs4cshS_5U63NSv0TO4c',URL:'https://api-seller.ozon.ru/v1/analytics/product-queries/details',RADAR:'06_Радар_1мин',PRODUCTS:'01_Товары',LOG:'04_Web_Позиции',HISTORY:'06_Радар_История',SETTINGS:'99_Настройки',FN:'ozonSellerPositionsFreeTick',HOURS:4,FIRST:5,MAXQ:15,PAGE:100,LOOKBACK:3,LAST:'OZON_FREE_POS_LAST_ATTEMPT_AT',MIN:220};
function ensureOzonSellerPositionsFreeTrigger_(){var a=ScriptApp.getProjectTriggers();for(var i=0;i<a.length;i++)if(a[i].getHandlerFunction()===OZON_FREE_POS.FN)return;ScriptApp.newTrigger(OZON_FREE_POS.FN).timeBased().everyHours(OZON_FREE_POS.HOURS).create()}
function setupOzonSellerPositionsFree(){ensureOzonSellerPositionsFreeTrigger_();PropertiesService.getScriptProperties().deleteProperty(OZON_FREE_POS.LAST);return ozonSellerPositionsFreeTick()}
function testOzonSellerPositionsFree(){PropertiesService.getScriptProperties().deleteProperty(OZON_FREE_POS.LAST);return ozonSellerPositionsFreeTick()}
function ozonSellerPositionsFreeTick(){var l=LockService.getScriptLock();if(!l.tryLock(5000))return{ok:false,skipped:'LOCKED'};try{var p=PropertiesService.getScriptProperties(),s=String(p.getProperty(OZON_FREE_POS.LAST)||''),d=s?new Date(s):null;if(d&&!isNaN(d.getTime())&&(Date.now()-d.getTime())/60000<OZON_FREE_POS.MIN)return{ok:true,skipped:'THROTTLED'};p.setProperty(OZON_FREE_POS.LAST,new Date().toISOString());var ss=SpreadsheetApp.openById(OZON_FREE_POS.SHEET_ID),r=ss.getSheetByName(OZON_FREE_POS.RADAR),pr=ss.getSheetByName(OZON_FREE_POS.PRODUCTS),lg=ss.getSheetByName(OZON_FREE_POS.LOG),h=ss.getSheetByName(OZON_FREE_POS.HISTORY);if(!r||!pr||!lg||!h)throw new Error('OZON_FREE_POS: sheet missing');var t=ofpTasks_(r);if(!t.length){ofpStatus_(ss,'READY · NO ENABLED TASKS','enabled=0');return{ok:true,tasks:0}}var map=ofpCab_(pr),g={},un=0;t.forEach(function(x){x.cab=String(map[x.sku]||'');if(!x.cab){un++;return}(g[x.cab]||(g[x.cab]=[])).push(x)});var lr=[],hr=[],ok=0,nq=0,er=[];Object.keys(g).sort().forEach(function(c){var cr=ofpCred_(c);if(!cr.id||!cr.key){er.push('cabinet '+c+': credentials not found');return}var a=g[c],sk=ofpUniq_(a.map(function(x){return x.sku})),f=ofpNewest_(cr,sk);if(!f.ok){er.push('cabinet '+c+': '+f.error);return}var bk={};(f.q||[]).forEach(function(z){var k=ofpKey_(z.sku,z.query);if(k)bk[k]=z});a.forEach(function(x){var m=bk[ofpKey_(x.sku,x.query)],at=f.date+'T00:00:00+03:00',src='Ozon Seller API · '+f.date;if(m&&isFinite(Number(m.position))&&Number(m.position)>0){var pos=Number(m.position),pv=ofpPrev_(lg,x.sku,x.query);if(pv===null)pv=x.cur;var de=pv&&isFinite(pv)?Number(pv)-pos:'';lr.push([at,x.art,x.sku,x.query,pos,pv===null?'':pv,de,'OK',OZON_FREE_POS.MAXQ,1,200,'/v1/analytics/product-queries/details',src]);hr.push([at,x.art,x.sku,x.query,pos,pv===null?'':pv,de,ofpRange_(pos),src,200,'','seller-api-'+f.date]);ok++}else{lr.push([at,x.art,x.sku,x.query,'','','','NO_QUERY_TOP15',OZON_FREE_POS.MAXQ,1,200,'/v1/analytics/product-queries/details',src]);nq++}})});if(lr.length)lg.getRange(lg.getLastRow()+1,1,lr.length,13).setValues(lr);if(hr.length)h.getRange(h.getLastRow()+1,1,hr.length,12).setValues(hr);var st=er.length?'PARTIAL · OFFICIAL OZON API':'ACTIVE · OFFICIAL OZON API',dt=['tasks='+t.length,'positions='+ok,'not_in_top15='+nq,un?'unresolved='+un:'',er.length?'errors='+er.join(' | ').substring(0,400):'',Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'dd.MM.yyyy HH:mm:ss')].filter(function(v){return v}).join('; ');ofpStatus_(ss,st,dt);SpreadsheetApp.flush();return{ok:!er.length,tasks:t.length,positions:ok,notInTop15:nq,errors:er}}finally{l.releaseLock()}}
function ofpTasks_(r){var n=r.getLastRow();if(n<OZON_FREE_POS.FIRST)return[];var v=r.getRange(OZON_FREE_POS.FIRST,1,n-OZON_FREE_POS.FIRST+1,16).getValues(),o=[];v.forEach(function(a){if(a[0]!==true)return;var art=String(a[1]||'').trim(),sku=String(a[2]||'').trim(),q=String(a[3]||'').trim(),c=Number(a[8]);if(art&&sku&&q)o.push({art:art,sku:sku,query:q,cur:isFinite(c)&&c>0?c:null})});return o}
function ofpCab_(s){var n=s.getLastRow(),m={};if(n<2)return m;s.getRange(2,1,n-1,4).getDisplayValues().forEach(function(a){var c=String(a[0]||'').trim(),sku=String(a[3]||'').trim();if(c&&sku&&!m[sku])m[sku]=c});return m}
function ofpCred_(c){var p=PropertiesService.getScriptProperties(),i,k;if(c==='1'){i=['OZON_CLIENT_ID_1','OZON1_CLIENT_ID','OZON_1_CLIENT_ID','OZON_CLIENT_ID1','OZON_CLIENT_ID'];k=['OZON_API_KEY_1','OZON1_API_KEY','OZON_1_API_KEY','OZON_API_KEY1','OZON_API_KEY']}else{i=['OZON_CLIENT_ID_'+c,'OZON'+c+'_CLIENT_ID','OZON_'+c+'_CLIENT_ID','OZON_CLIENT_ID'+c];k=['OZON_API_KEY_'+c,'OZON'+c+'_API_KEY','OZON_'+c+'_API_KEY','OZON_API_KEY'+c]}return{id:ofpProp_(p,i),key:ofpProp_(p,k)}}
function ofpProp_(p,a){for(var i=0;i<a.length;i++){var v=String(p.getProperty(a[i])||'').trim();if(v)return v}return''}
function ofpNewest_(c,s){var tz=Session.getScriptTimeZone()||'Europe/Moscow',now=new Date(),e='';for(var a=1;a<=OZON_FREE_POS.LOOKBACK;a++){var d=Utilities.formatDate(new Date(now.getTime()-a*86400000),tz,'yyyy-MM-dd');try{var q=ofpFetch_(c,s,d);if(q.length)return{ok:true,date:d,q:q}}catch(x){e=String(x&&x.message?x.message:x);if(e.indexOf('HTTP 401')>=0||e.indexOf('HTTP 403')>=0)return{ok:false,error:e}}}return{ok:false,error:e||'no calculated data for T-1..T-3'}}
function ofpFetch_(c,s,d){var all=[],pg=0,pc=1;while(pg<pc&&pg<50){var body={date_from:d,date_to:d,limit_by_sku:OZON_FREE_POS.MAXQ,page:pg,page_size:OZON_FREE_POS.PAGE,skus:s,sort_by:'BY_SEARCHES',sort_dir:'DESCENDING'},hd={Accept:'application/json'};hd['Client'+'-Id']=c.id;hd['Api'+'-Key']=c.key;var r=UrlFetchApp.fetch(OZON_FREE_POS.URL,{method:'post',contentType:'application/json',headers:hd,payload:JSON.stringify(body),muteHttpExceptions:true}),code=r.getResponseCode(),tx=r.getContentText()||'';if(code<200||code>=300)throw new Error('Ozon Seller API HTTP '+code+': '+tx.substring(0,350));var j;try{j=tx?JSON.parse(tx):{}}catch(e){throw new Error('Ozon Seller API invalid JSON')}var q=Array.isArray(j.queries)?j.queries:[];q.forEach(function(x){all.push(x)});pc=Math.max(1,Number(j.page_count||1));pg++}return all}
function ofpPrev_(s,sku,q){var n=s.getLastRow();if(n<3)return null;var st=Math.max(3,n-4997),v=s.getRange(st,3,n-st+1,6).getDisplayValues();for(var i=v.length-1;i>=0;i--)if(String(v[i][0]||'').trim()===String(sku)&&ofpNorm_(v[i][1])===ofpNorm_(q)&&String(v[i][5]||'').trim()==='OK'){var p=Number(v[i][2]);return isFinite(p)&&p>0?p:null}return null}
function ofpKey_(s,q){s=String(s==null?'':s).trim();q=ofpNorm_(q);return s&&q?s+'|'+q:''}
function ofpNorm_(v){return String(v||'').toLowerCase().replace(/ё/g,'е').replace(/\s+/g,' ').trim()}
function ofpUniq_(a){var s={},o=[];a.forEach(function(v){v=String(v||'').trim();if(v&&!s[v]){s[v]=1;o.push(v)}});return o}
function ofpRange_(p){p=Number(p||0);return p<=10?'TOP-10':p<=50?'TOP-50':p<=100?'TOP-100':p<=500?'101–500':'500+'}
function ofpStatus_(ss,st,dt){var s=ss.getSheetByName(OZON_FREE_POS.SETTINGS);if(!s)return;var n=Math.max(1,s.getLastRow()),v=s.getRange(1,1,n,3).getDisplayValues(),r=0;for(var i=0;i<v.length;i++)if(String(v[i][0]||'').trim()==='RADAR_STATUS'){r=i+1;break}if(!r){r=s.getLastRow()+1;s.getRange(r,1,1,3).setValues([['RADAR_STATUS','','']])}s.getRange(r,2,1,2).setValues([[String(st||''),String(dt||'')]])}
